// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

// 数据未查询到
func IsDataNotfand(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_NOTFAND.String() && e.Code == 200
}

// 数据未查询到
func ErrorDataNotfand(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_DATA_NOTFAND.String(), fmt.Sprintf(format, args...))
}

// 订单不允许重复评价
func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

// 订单不允许重复评价
func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 评价不允许重复回复
func IsReviewHasreply(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_HASREPLY.String() && e.Code == 300
}

// 评价不允许重复回复
func ErrorReviewHasreply(format string, args ...interface{}) *errors.Error {
	return errors.New(300, ErrorReason_REVIEW_HASREPLY.String(), fmt.Sprintf(format, args...))
}

// 不允许回复非当前店铺的评价
func IsReviewNotcurrentstore(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_NOTCURRENTSTORE.String() && e.Code == 301
}

// 不允许回复非当前店铺的评价
func ErrorReviewNotcurrentstore(format string, args ...interface{}) *errors.Error {
	return errors.New(301, ErrorReason_REVIEW_NOTCURRENTSTORE.String(), fmt.Sprintf(format, args...))
}
